### PR TITLE
Fix build with stable Nix

### LINKED ISSUE #60: Failed to compile on aarch64-darwin
```
[1/2] Compiling C++ object src/nix-eval-jobs.p/nix-eval-jobs.cc.o
[2/2] Linking target src/nix-eval-jobs
FAILED: src/nix-eval-jobs
clang++  -o src/nix-eval-jobs src/nix-eval-jobs.p/nix-eval-jobs.cc.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error /nix/store/7dh9a3rlriwdp8j9120vwwp5s3aqr8yd-nix-2.8.0/lib>
Undefined symbols for architecture arm64:
  "nix::MixEvalArgs::getAutoArgs(nix::EvalState&)", referenced from:
      Proc::Proc(std::__1::function<void (nix::EvalState&, nix::Bindings&, nix::AutoCloseFD&, nix::AutoCloseFD&)> const&)::'lambda'()::operator()() const in nix-eval-jobs.cc.o
  "nix::MixEvalArgs::MixEvalArgs()", referenced from:
      MyArgs::MyArgs() in nix-eval-jobs.cc.o
  "nix::lookupFileArg(nix::EvalState&, std::__1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      releaseExprTopLevelValue(nix::EvalState&, nix::Bindings&) in nix-eval-jobs.cc.o
ld: symbol(s) not found for architecture arm64
```

2e3405f2d10358fd1dde5712b7b61ee7243462d3, NixOS/nixpkgs@3c0f57e36ed0cf9947281e3b31f1bebb7ce5d4a1.

### PR DESCRIPTION
**Pull request by adisbladis**
Closes #60

### CODE REVIEW

**Review by winterqt — APPROVED** [review]
Tested and works, thanks!

**Comment by winterqt** [comment]
I think calling this stable Nix may be a bit misleading -- I'm on nixUnstable. (Unless a new Nix release is/was cut recently? Not sure.)

**Comment by adisbladis** [comment]
> I think calling this stable Nix may be a bit misleading -- I'm on nixUnstable. (Unless a new Nix release is/was cut recently? Not sure.)

2.8.0 was cut 4 days ago.

**Comment by adisbladis** [comment]
Nixpkgs PR in https://github.com/NixOS/nixpkgs/pull/170039.

**Pull request merged**
