### PR TITLE
fix: use `InstallableFlake` type & methods

### LINKED ISSUE #134: `--flake` fails if the `outputs` contain a `__functor`
This command always fails on a flake whos `outputs` contains a `__functor` attribute. The error is a type where target is said to be a function and should be an attribute-set, even if the flake uri points to a valid attribute-set.

### PR DESCRIPTION
**Pull request by nrdxp**
Fixes #134

Use the `InstallableFlake` type in order to make use of it's `toValue` method. This fixes the functor auto-call by including the work from nixos/nix#6404.

Future work may make use of this object and its methods to employ the flake based eval cache.

### CODE REVIEW

**Comment by Mic92** [comment]
bors merge

**Comment by Mic92** [comment]
bors merge

**Comment by blaggacao** [comment]
For some reason Bors did time out? We're eager to make solid use of this ... :small_airplane:

**Comment by Mic92** [comment]
I think its because the bors.toml was not yet in this fork.

**Pull request merged**
