### PR TITLE
Add flag to enable trace output

### PR DESCRIPTION
**Pull request by zhaofengli**
This PR adds `--show-trace` which adds stack traces to the outputs when evaluation errors occur, matching `nix-instantiate` and other Nix commands.

### CODE REVIEW

**Comment by adisbladis** [comment]
I'm not quite sure what I think about outputting to `stderr` since each individual error key also contains the full stack trace.
I'm open to be convinced though.

**Comment by adisbladis** [comment]
It's important to note that `nix-eval-jobs` is very semantically different to `nix-instantiate`.

The latter will bail out on the first evaluation error, so the output is immediately useful while `nix-eval-jobs` is machine-friendly output first and it's up to the caller to terminate on any evaluation errors, so the error output is less useful.

**Comment by adisbladis** [comment]
On the whole though, this is awesome and I'm very happy to see stack traces using this tool!

**Comment by zhaofengli** [comment]
> I'm not quite sure what I think about outputting to stderr since each individual error key also contains the full stack trace.

> It's important to note that `nix-eval-jobs` is very semantically different to `nix-instantiate`.
>
> The latter will bail out on the first evaluation error, so the output is immediately useful while `nix-eval-jobs` is machine-friendly output first and it's up to the caller to terminate on any evaluation errors, so the error output is less useful.

Good point! Let's still print the short `e.msg()` to make the output less cluttered.

**Comment by adisbladis** [comment]
> Good point! Let's still print the short e.msg() to make the output less cluttered.

I still find it a bit noisy :/
Also I just realised it's racy since the call to `printError` is happening in the worker thread.

**Comment by zhaofengli** [comment]
> I still find it a bit noisy :/

Hmm, the updated PR doesn't change what's printed to stderr at all, and the stack traces are only added to the JSON lines. Perhaps I misunderstood what you meant?

> Also I just realised it's racy since the call to `printError()` is happening in the worker thread.

We could perform the printing ourselves and have a mutex instead of relying on Nix's `printError`. Ideally this should also be solved on Nix's end.

**Comment by adisbladis** [comment]
> Hmm, the updated PR doesn't change what's printed to stderr at all, and the stack traces are only added to the JSON lines. 

Sorry, my bad!

I think this PR is looking good now.

**Pull request merged**
