### PR TITLE
Remove findAlongAttrPath.

### LINKED ISSUE #10: Cut off cyclic evaluations
The evaluator should probably keep track of when the evaluation goes cyclic.

Eg:

`repro.nix`
```
{ system ? builtins.currentSystem }:
let
  x = {
    recurseForDerivations = true;

    drv = derivation {
      inherit system;
      name = "xxx";
      builder = ":";
    };

    x = x;
  };
in
x
```

```console
$ $ nix-eval-jobs repro.nix |& head -n 20
warning: `--gc-roots-dir' not specified
error: attribute 'recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
error: attribute 'x.x.x.x.x.x.x.x.x.x.x.x.x.x.recurseForDerivations' is a Boolean, which is not supported
{"attr":"drv","drvPath":"/nix/store/gg50kx4h02cg749cfkib8diz8g2dgq7n-xxx.drv","name":"xxx","system":"x86_64-linux"}
{"attr":"recurseForDerivations","error":"error: attribute 'recurseForDerivations' is a Boolean, which is not supported"}
{"attr":"x.drv","drvPath":"/nix/store/gg50kx4h02cg749cfkib8diz8g2dgq7n-xxx.drv","name":"xxx","system":"x86_64-linux"}
{"attr":"x.recurseForDerivations","error":"error: attribute 'x.recurseForDerivations' is a Boolean, which is not supported"}
```

### LINKED ISSUE #42: What is the file supposed to look like?
I was confused first by the fact that the cli's positional parameter is documented as `expr` but in fact only accepts a file. Then I was confused by the expected format of the file. Is it supposed to be a hydra jobset? If so, the hydra jobset documentation is currently giving a 500 error: https://hydra.nixos.org/job/hydra/master/manual/latest/download-by-type/doc/manual#idm140737315920320

_Originally posted by @jsoo1 in https://github.com/nix-community/nix-eval-jobs/issues/41#issuecomment-1058835360_

### PR DESCRIPTION
**Pull request by jsoo1**
To avoid type confusion between AttrPath and Symbol.

Closes #42
Closes #10 

To accomplish this, use an `Accessor` class to provide polymorphic ways of of projecting out of a nix value. There are two cases for `nix-build` compatibility:

* `Name` - an attribute name to select from an attrset.
* `Index` - an index in a list.

The nice part about these is they can both be nicely serialized to json, which we already use.  The rest is bookkeeping:

1. Start a process to collect the top-level `Accessor`s when the process starts and put them in the state's todos.
2. Receive the `Accessor`s as json in the worker processes and be careful to parse everything and handle errors.
3. Use the `Accessor`s method of getting in a `Value` instead of `findAlongAttrPaths`

The rest of the process is as before, except don't handle recursing into further expressions. Since `nix-build` handles one of a derivation, or a list or set thereof, just handle those. No need to keep collecting accessors or attrpaths.

### CODE REVIEW

**Comment by jsoo1** [comment]
Closes #42 

Note that this revision breaks flake evaluation.

**Comment by jsoo1** [comment]
This is still a draft and it is definitely a work in progress, but I think the basic case (without flakes) are working. This revision handles a file that is one of:
- A derivation
- An attrset of derivation
- A list of derivation
I'm not sure this covers everything from `nix-build` after further perusal of the implementation, but do we want to support _everything_ that it does? There really is a lot of magic in the cli commands of nix.

**Comment by jsoo1** [comment]
There is a fair bit of refactoring in here. Mostly to facilitate reuse of forking procedure and derivation collection/jsonification.

**Comment by jsoo1** [comment]
I opened #55, #56, and #57 upon which this PR depends. If you would like me to reorganize to get this in sooner, or something, I'd be happy to do so.

**Comment by jsoo1** [comment]
Cleaned up the commit history. There are three squashed commits that correspond to the speculative merge of #55, #56, and #57. The commits afterward are reviewable independently.

**Comment by jsoo1** [comment]
I think this is closer to solving #9, but is not quite there yet.

**Comment by jsoo1** [comment]
Well this is rebased and tests pass. So I think this is pretty much ready for review. I think there are some missing features (?) here. For instance, I think nixos system definitions will fail here. I have a hacky workaround for that, in a fork. But in general, `nix-eval-jobs` would do what it says on the tin after this merges.

**Comment by adisbladis** [comment]
I have rebased this PR on latest main to incorporate #59.

**Comment by adisbladis** [comment]
@jsoo1 Could you take a look at #64 as an intermediate before this PR is ready?

Also, I'd like for some of the comment/doc edits to be split into a separate PR if applicable

**Comment by jsoo1** [comment]
Sure. Sorry I got carried away. I will walk it back some if you wish.  Same with doc/readme changes. Those are less relevant now anyways, since nested expressions are desired.

**Comment by jsoo1** [comment]
Closing in favor of #62

**Pull request closed without merging**
