### PR TITLE
feat: add inputDrvs to the JSON

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Currently, not a lot of things expose inputDrvs (except `show-derivation`), which is a showstopper whenever you want to compute popularity ranking based on the dependency relation.

Having `inputsDrvs` in the reply enable downstream users to perform such computations efficiently.

I'm still trying to understand how I want to use this, cc @Mic92

### CODE REVIEW

**Comment by Mic92** [comment]
Looks like a good thing to have. I guess this would not add a lot of overhead?

**Comment by adisbladis** [comment]
> I guess this would not add a lot of overhead?

It shouldn't add any eval overhead as `inputDrvs` has already been computed as a part of calculating the derivation hash.

**Comment by RaitoBezarius** [comment]
As a point of reference, it took me 18 hours to run `./src/nix-eval-jobs --gc-roots-dir gcroot -I ~lnixpkgs ../outpaths.nix --check-cache-status --arg checkMeta true --argstr path ~lnixpkgs --meta > eval`

where `outpaths.nix` is the file coming from ofborg, with this patch. Generating a 578MiB eval JSON.

I surmise I was running with debug though… :D.

**Comment by adisbladis** [comment]
> As a point of reference, it took me 18 hours to run

On a related note I'd like to get an idea how much overhead `--meta` adds for these larger evals.

**Comment by Mic92** [comment]
> As a point of reference, it took me 18 hours to run `./src/nix-eval-jobs --gc-roots-dir gcroot -I ~lnixpkgs ../outpaths.nix --check-cache-status --arg checkMeta true --argstr path ~lnixpkgs --meta > eval`
> 
> where `outpaths.nix` is the file coming from ofborg, with this patch. Generating a 578MiB eval JSON.
> 
> I surmise I was running with debug though… :D.
> 
> on a weak 64GiB RAM T480 laptop with Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz.

What is outpaths.nix?

**Comment by Mic92** [comment]
nix-eval-jobs already can handle recurseIntoAttrs in hopefully the same way hydra does it: https://github.com/NixOS/ofborg/blob/0f34038feb9b0ae9959c865608700c91d57b2590/ofborg/src/outpaths.nix#L48 So we might not need this.

**Comment by RaitoBezarius** [comment]
For you full pleasure:
```
[root@nixos:~/nix-eval-jobs]# time ./result/bin/nix-eval-jobs --max-memory-size 1024 --workers 96 --gc-roots-dir gcroot -I ~/nixpkgs ./outpaths.nix --argstr path ~/nixpkgs --arg checkMeta false &> eval-without-meta

real    8m48.418s
user    192m35.048s
sys     118m47.847s
```

EPYC 7763, 128G of RAM for the specifications.
~500-800 derivation/s measured by `pv --line-mode --rate` on the `eval-without-meta`, sometimes 1-2K/s.

**Comment by RaitoBezarius** [comment]
```
raito@amy:~/nix-eval-jobs/ > time ./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir gcroot -I ~/nixpkgs ./outpaths.nix --argstr path ~/nixpkgs --arg checkMeta false &> eval-without-meta
./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir  3955.24s user 1432.31s system 383% cpu 23:24.84 total
```

Dual-CPU EPYC 7413 (24-core), 256G of RAM.
~80-100 derivation/s, sometimes 400-600 derivation/s.

Now checking with meta.

**Comment by RaitoBezarius** [comment]
```
raito@amy:~/nix-eval-jobs/ > time ./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir gcroot -I ~/nixpkgs ./outpaths.nix --argstr path ~/nixpkgs --meta --arg checkMeta true &> eval-with-
meta
./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir  15804.80s user 5863.21s system 4400% cpu 8:12.37 total
```

Dual-CPU EPYC 7413 (24-core), 256G of RAM.
~400-600 derivation/s, sometimes 1000-1500 derivation/s.

**Comment by RaitoBezarius** [comment]
```

[root@nixos:~/nix-eval-jobs]# time ./result/bin/nix-eval-jobs --max-memory-size 1024 --workers 96 --gc-roots-dir gcroot --meta -I ~/nixpkgs ./outpaths.nix --argstr path ~/nixpkgs --arg checkMeta true &> eval-with-meta
aa
real    38m36.672s
user    1543m15.020s
sys     2158m9.380s
```

EPYC 7763, 128G of RAM.
~80-120 derivation/s, sometimes 400 derivation/s.

**Comment by RaitoBezarius** [comment]
Okay, hot evaluation without meta:
```
raito@amy:~/nix-eval-jobs/ > time ./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir gcroot -I ~/nixpkgs ./outpaths.nix --argstr path ~/nixpkgs --arg checkMeta false &> eval-without-meta
./result/bin/nix-eval-jobs --max-memory-size 2048 --workers 80 --gc-roots-dir  5464.24s user 2111.23s system 3415% cpu 3:41.80 total
```

Dual-CPU EPYC 7413 (24-core), 256G of RAM.
It was like 2-5K derivation/s.

**Pull request merged**
